- hosts: localhost
  become: true
  pre_tasks:
    - name: update arch repositories
      pacman: 
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'archlinux'
    
    - name: update deb repositories
      apt:
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'debian'

  tasks:
    - include: tasks/packages.yml
